name: "Merge Shupin Dict"
description: "Automatically merge parts of the dict as one after commits"
author: "amorphobia"
branding:
  icon: git-merge
  color: blue
inputs:
  token:
    description: "Token for the repo"
    required: true
  contents:
    default: "contents/*.txt"
    required: false
  dict:
    default: "shupin.dict.yaml"
    required: false
  branch:
    default: "master"
    required: false

runs:
  using: "node12"
  main: "index.js"
