name: "Merge Shupin Dict"
description: "Automatically merge parts of the dict as one after commits"
author: "amorphobia"
branding:
  icon: git-merge
  color: blue
inputs:
  contents:
    default: "contents/*.txt"
    required: false
  dict:
    default: "shupin.dict.yaml"
    required: false
  branch:
    default: "master"
    required: false

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: List files
      run: |
        ls -lh $INPUT_CONTENTS
        ls -lh $INPUT_DICT
        echo $GITHUB_ACTOR
        echo $GITHUB_REPOSITORY
    
    - name: Merge files
      run: |
        cat $INPUT_CONTENTS > $INPUT_DICT
    
    - name: Test modified
      id: test_modified
      run: |
        if [ "$(git diff $INPUT_Dict)" != "" ]; then
          echo "##[set-output name=changed;]true"
        fi
    
    - name: Commit files
      if: ${{ steps.test_modified.outputs.changed == 'true' }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Github Action"
        git add $INPUT_DICT
        git commit -m "Merge contents to dict"
    
    - name: Push changes
      if: ${{ steps.test_modified.outputs.changed == 'true' }}
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push "https://${github_token}@github.com/${GITHUB_REPOSITORY}.git" HEAD:${INPUT_BRANCH}
